{
  "hash": "115c3278b5a18cd6a79f959f170afbdf",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"May ponds and breeding ducks in Prairie Canada, 1955–2026\"\nauthor: \"{{< var author.name >}}\"\ndate: last-modified\ndate-format: \"MMMM YYYY\"\nbibliography: references.bib\nfig-width: 6.5\ntbl-colwidths: false\nknitr:\n  opts_chunk:\n    dev: ragg_png\nformat:\n  typst:\n    output-file: prairie-ducks-methods.pdf\n    citeproc: true\n    include-in-header:\n      text: |\n        #show table: set text(size: 8.5pt)\n        #show table.cell: set par(justify: false)\n    mainfont: \"Source Serif 4\"\n    font-paths: [assets/fonts]\n    fontsize: 10pt\n    papersize: us-letter\n    margin:\n      x: 1in\n      y: 0.9in\n    fig-dpi: 250\n---\n\n\n\n## Summary\n\nThe web version, which includes an interactive wetland-loss calculator along with the data downloads, is available at [{{< var site >}}]({{< var site >}}).\n\n::: {.abstract}\n**Question:** How closely do ducks breeding in Prairie Canada follow the number of ponds present across the landscape in May? How does this relationship differ among species, and has it changed since the 1950s?\n\n**Data and model:** I used stratum estimates from the Waterfowl Breeding Population and Habitat Survey for the 15 strata of southern Alberta, Saskatchewan, and Manitoba, covering 70 surveys from 1955 to 2026. For five species of dabbling ducks and the canvasback, I modelled the relationship between breeding population and May ponds using a hierarchical generalized additive model assuming a Tweedie error distribution. As smooth trends for the region and each stratum absorbed gradual changes, pond effects expressed as elasticity were estimated from year-to-year fluctuations in water availability.\n\n**Results:** Across the most recent ten surveys, a sustained 1% change in May ponds was associated with a change in the breeding population of Northern Pintail (1.30%; 95% interval 1.01 to 1.60) and Mallards (0.32%; 0.17 to 0.45), with changes for other species falling between these values. Pond elasticity for pintail increased from 0.79 during 1956–1965 to 1.25 in recent years. However, this increase was smaller in the more conservative model that accounted for shocks shared across all strata in each year. Applied to recent population sizes, the main model implies that a 10% loss of May ponds throughout Prairie Canada would reduce the number of breeding dabbling ducks by about 660,000 individuals (90% interval 575,000 to 727,000).\n\n**Caveat:** These elasticities describe responses to naturally occurring wet and dry years. Due to the permanent nature of drainage and the tendency for drainage to remove small basins first, the loss estimates serve as reference points rather than predictions.\n:::\n\n## Introduction\n\nThe prairie pothole region across southern Alberta, Saskatchewan, and Manitoba contains millions of small, shallow wetlands, and in a wet spring the region draws a large proportion of North America's breeding dabbling ducks. Since 1955, the U.S. Fish and Wildlife Service and Canadian Wildlife Service have conducted the Waterfowl Breeding Population and Habitat Survey (WBPHS) by aircraft each May, counting ducks and ponds along the same set of transects [@smith1995]. These records now span 70 surveys, matching bird populations with their habitat conditions from year to year.\n\nThe tendency for ducks to follow water is well established [@johnson1988; @bethke1995]. However, the strength of this relationship across species, whether this relationship has changed as prairie has been converted to cropland, and the implications for the number of breeding ducks corresponding to wetlands that have been lost remain less settled. These questions are important for conservation planning, as small wetlands in the Canadian prairies continue to undergo drainage, and Northern Pintail numbers have not recovered. Across the most recent ten surveys, the number of pintails in the Canadian prairies averaged 85% lower than the 1955 to 1964 average. @podruzny2002 examined long-term associations among pintails, wetlands, and agriculture in this region, and more recent work linked pintail declines to cropland through where pintails nest and how many young they raise [@zhao2019; @buderman2020].\n\nThis analysis revisits these questions with the full survey record, using one model structure for six species. It asks three questions of the public WBPHS stratum estimates:\n\n1. What is the pond elasticity of each species, the percent change in breeding birds that goes with a 1% change in May ponds?\n2. Has it changed since the survey began?\n3. What does it imply for a given loss of ponds?\n\n## Data\n\n### Survey and study area\n\nEach May, observers in fixed-wing aircraft count ducks and ponds along transects crossing each stratum of the survey. Ground observers repeat counts in a subset of segments to correct the aerial counts for birds missed from the aircraft. The U.S. Fish and Wildlife Service publishes the resulting breeding population estimates (BPOP) by stratum, species, and year, together with the number of May ponds and the standard errors associated with these estimates [@smith1995; @eyler2026].\n\nI used the 15 strata of Prairie Canada (@fig-study), comprising 26 to 29 in southern Alberta, 30 to 35 in southern Saskatchewan, and 36 to 40 in southern Manitoba. The strata range from about 13,000 to 100,000 km². Aerial surveys were not conducted in 2020 and 2021, resulting in 70 surveys between 1955 and 2026. Stratum 36 was also not surveyed in 2002 and 2023, and prairie-wide totals for those years excluded this stratum. In the surveys either side of those years, the pond count in this stratum accounted for at most 1.9% of the prairie-wide pond total, and this stratum held at most 1.7% of any species' breeding birds.\n\nI studied five species of dabbling ducks that dominate the prairie breeding population (Mallard, Northern Pintail, Blue-winged Teal, Gadwall, and Northern Shoveler), all of which nest on uplands. Additionally, I included Canvasback, which nests over water, for comparison.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The 15 WBPHS strata in Prairie Canada that I used in this analysis. Strata 26–29 are in Alberta, 30–35 in Saskatchewan, and 36–40 in Manitoba. Grey outlines to the south indicate strata 41–49 in the United States, which were not included in the modelling.](methods_files/figure-typst/fig-study-1.png){#fig-study fig-alt='Map of southern Alberta, Saskatchewan, and Manitoba divided into 15 numbered survey strata, from 26 in the northwest to 40 in the southeast.'}\n:::\n:::\n\n\n### Preparation\n\nThe distributed files listed only the species observed in each stratum. I filled in zeros for all strata and years with an aerial survey, treating unobserved species as zeros rather than missing values. Standard errors recorded as \"NULL\" were treated as missing values. I log-transformed pond counts and centred these within each stratum, such that the pond variable in the model represented deviations from the typical log pond count for that stratum. I included the previous year's pond count in the model only when a survey had been conducted in the preceding calendar year. Thus, I excluded 1955, the first spring following the 2020–21 interruption, and the springs following missing years in stratum 36, retaining 1,016 combinations of stratum and year for each species.\n\n@fig-trends shows the prairie-wide counts of May ponds and individual breeding dabbling ducks, aggregated across 15 strata, that formed the underlying data.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![May ponds (upper panel) and numbers of breeding dabbling ducks stacked by species (lower panel) in Prairie Canada during 1955–2026. Values shown are totals for survey strata 26–40. Yellow shaded bands indicate the ten driest springs. The gap corresponds to 2020–21, when aerial surveys were not conducted.](methods_files/figure-typst/fig-trends-1.png){#fig-trends fig-alt='Two charts sharing a time axis. Ponds swing between about 1.4 and 7.3 million with no strong trend. Dabbling ducks, stacked by species with Northern Pintail at the bottom, fall from about 20 million in the mid-1950s to between 5 and 16 million, rising and falling with ponds. The pintail band narrows over time.'}\n:::\n:::\n\n\n## Model\n\n### Structure\n\nFor each species I fitted a hierarchical generalized additive model [@pedersen2019] to the breeding population estimate $y_{st}$ in stratum $s$ and year $t$:\n\n$$\n\\begin{aligned}\ny_{st} &\\sim \\text{Tweedie}(\\mu_{st},\\ \\phi / w_{st},\\ p), \\qquad 1 < p < 2, \\\\\n\\log \\mu_{st} &= \\alpha + f(t) + f_s(t) + \\left[\\beta(t) + b_s\\right] x_{st} + \\gamma\\, x_{s,t-1},\n\\end{aligned}\n$$\n\nwhere $x_{st}$ is log May ponds centred within the stratum. The terms are:\n\n- $f(t)$, a smooth prairie-wide trend (thin-plate basis, 20 functions);\n- $f_s(t)$, a smooth trend for each stratum, penalized towards zero and sharing one smoothing parameter (a factor-smooth interaction, 10 functions each; the \"GS\" model of @pedersen2019);\n- $\\beta(t)$, the prairie-wide pond elasticity, allowed to change smoothly over time (8 functions);\n- $b_s \\sim N(0, \\sigma_b^2)$, each stratum's departure from that elasticity;\n- $\\gamma$, the carry-over from last year's ponds.\n\nThe trend terms account for gradual changes within each stratum, regardless of their cause. Thus, the pond terms are estimated from year-to-year variation, reflecting whether bird abundance in a stratum was higher than predicted by the trend in years when water was more abundant than usual in that stratum.\n\nA Tweedie distribution with an estimated power parameter $p$ handles zero counts for relatively rare species in some strata without adding a constant before log transformation. Weights $w_{st}$ reflect the precision of the survey itself in model fitting:\n\n$$\nw_{st} \\propto \\frac{1}{\\mathrm{CV}_{st}^2 + \\operatorname{median}(\\mathrm{CV}^2)},\n$$\n\nwhere $\\mathrm{CV}_{st}$ is the estimate's coefficient of variation. The median term provides a lower bound for variation not captured by the survey standard errors, preventing the most precise stratum and year combinations from dominating. For zero estimates and estimates without standard errors, I used the median CV. I adjusted the weights to have a mean of 1 within each species.\n\nModels were fitted with `mgcv::bam()` by fast REML with discretized covariates [@wood2011; @wood2017]:\n\n```r\nbam(\n  estimate ~ s(year, k = 20) +                        # Prairie-wide trend, f(t)\n    s(year, stratum_f, bs = \"fs\", k = 10, m = 2) +    # trend for each stratum, f_s(t)\n    s(year, by = log_ponds_c, k = 8) +                # pond elasticity over time, beta(t)\n    s(stratum_f, log_ponds_c, bs = \"re\") +            # Deviations by stratum, b_s\n    log_ponds_lag_c,                                  # Previous year's ponds, gamma\n  family = tw(), weights = w, data = d,\n  method = \"fREML\", discrete = TRUE\n)\n```\n\n### Pond elasticity\n\nWith a log link function and log-transformed pond counts, the coefficient for pond count represents elasticity. For stratum $s$ in year $t$, **short-term elasticity** is $e_{st} = \\beta(t) + b_s$, representing the percent change in breeding birds associated with a 1% change in pond count that spring. The **sustained elasticity** adds the carry-over to the short-term elasticity, giving $e_{st} + \\gamma$, which represents the response when a change in pond count is sustained over two springs; the model considers no earlier history. Prairie averages are unweighted means across 15 strata, with each stratum contributing equally regardless of area or number of birds. \"Recent\" refers to the most recent ten surveys, namely 2015–2019 and 2022–2026.\n\n### Uncertainty\n\nFor each model, I sampled 300 sets of coefficients from an approximate posterior represented by a multivariate normal distribution centred on the estimates, with covariance corrected to account for smoothing parameter uncertainty (`vcov(m, unconditional = TRUE)`). Within each draw, I calculated elasticity exactly for all stratum and year combinations using the difference between two rows of the model linear predictor matrix, one using $x_{st} = 1$ and one using $x_{st} = 0$. All summaries (curves, maps, tables, and the calculator on the web page) were first calculated within each draw and then summarized across draws. I reported elasticity with a 95% interval and scenario totals with a 90% interval, both obtained from quantiles across draws. As each draw retained the correlations among strata and among years in the model, the interval for a sum or difference was not constructed from the respective individual intervals.\n\n### Scenarios\n\nFor a proportional loss $\\ell$ of May ponds in stratum $s$, the change in breeding birds of one species is\n\n$$\n\\Delta_s = \\bar{B}_s \\left[ (1 - \\ell)^{e_s} - 1 \\right],\n$$\n\nwhere $\\bar{B}_s$ is the stratum's mean breeding population for the most recent ten surveys, and $e_s$ is the mean elasticity over the same years, referring to sustained elasticity unless otherwise stated. Within each draw, changes are summed across the selected strata and species. For a small loss distributed across all strata in proportion to the pond count in each stratum, the number of breeding individuals per pond lost is $\\sum_s e_s \\bar{B}_s / \\sum_s \\bar{P}_s$, where $\\bar{P}_s$ is the mean pond count for the stratum in recent years.\n\n### Checks\n\nI refitted every model three ways to see how much the answers depend on modelling choices:\n\n- **trend basis doubled**: 40 functions for the prairie-wide trend and 20 for each stratum;\n- **AR(1) residuals**: first-order autocorrelation within each stratum's run of consecutive years, with $\\rho = 0.2$, above the mean lag-1 residual autocorrelation of every main fit;\n- **year effects**: a random intercept for each survey year, which absorbs any shock shared by all strata that spring, such as weather, timing, or conditions farther north. The pond effect is then estimated mainly from differences among strata within the same year.\n\nI checked the basis dimension using `mgcv::k.check()` and examined residual autocorrelation within each stratum. To validate the data, I summed the file, then compared the resulting totals with the annual status reports. The total for Mallards in the traditional survey area was 9,423,417 in 2019 and 6,609,306 in 2024, and May ponds in Prairie Canada numbered 2,855,574 and 2,681,246, respectively. When rounded, these values agreed with the published figures for Mallards (9.4 and 6.6 million) and ponds (2.9 and 2.7 million) [@usfws2019; @usfws2024]. This comparison is repeated each time the pipeline runs, and the pipeline stops if any rounded total no longer agrees with the published value.\n\nThe wetland-loss calculator on the web page runs in the browser, and I therefore implemented the calculations in both R and JavaScript. Each time the pipeline is run, the page's JavaScript is executed within R (through the V8 engine) using the exported draws as input, and the results are compared with those from the R implementation for five fixed scenarios; processing stops if the results do not agree. The maximum relative difference was 4e-16, which was at the level of machine precision.\n\n## Results\n\n### Model fit\n\nThe models explained 84% to 95% of the deviance (@tbl-diag), with estimated Tweedie power parameters ranging from 1.30 to 1.55. Carry-over from the previous year's pond counts was positive across all species, ranging from 0.04 (SE 0.03) for Northern Pintail to 0.22 for Canvasback.\n\n\n::: {#tbl-diag .cell tbl-cap='Model fit and diagnostics. The carry-over effect is the coefficient for the log of the previous year\\'s pond count, reported alongside the standard error. The k-index is the minimum across all smooth terms. Residual autocorrelation is at lag 1 within strata, averaged over strata, with the maximum absolute stratum autocorrelation also reported.'}\n::: {.cell-output-display}\n\n\n|Species           | Deviance explained| Tweedie p| Carry-over (SE)| Smallest k-index| Residual autocorrelation|\n|:-----------------|------------------:|---------:|---------------:|----------------:|------------------------:|\n|Northern Pintail  |                92%|      1.39|     0.04 (0.03)|             0.63|              −0.04, 0.22|\n|Northern Shoveler |                91%|      1.33|     0.13 (0.03)|             0.72|               0.12, 0.37|\n|Blue-winged Teal  |                87%|      1.41|     0.18 (0.03)|             0.68|               0.13, 0.33|\n|Canvasback        |                84%|      1.30|     0.22 (0.03)|             0.75|              −0.02, 0.17|\n|Gadwall           |                93%|      1.31|     0.11 (0.03)|             0.73|               0.10, 0.30|\n|Mallard           |                95%|      1.55|     0.10 (0.02)|             0.64|               0.01, 0.31|\n\n\n:::\n:::\n\n\nTwo diagnostic results require cautious interpretation. The lowest k-index values ranged from 0.63 to 0.75, with values below 1 indicating that some temporally ordered pattern remained in the residuals. Doubling the number of basis functions for the trend produced little change in the k-index (0.63 to 0.76); thus, increasing trend flexibility did not remove this pattern. Adding year effects raised the k-index to 0.74 to 0.81, suggesting that the pattern reflected shocks shared across strata in particular years rather than trends that were too stiff. Residual autocorrelation at lag 1 averaged across strata ranged from −0.04 to 0.13, but reached 0.37 in individual strata. The sensitivity refits below will show the extent to which these issues affect elasticity.\n\n### Elasticity by species\n\nSpecies rankings based on pond elasticity were the same for short-term elasticity and sustained elasticity (@tbl-elasticity). Northern Pintail showed the greatest response, with a sustained 1% change in pond numbers corresponding to a 1.30 (95% interval 1.01 to 1.60) percent change in breeding birds. Mallard showed the smallest response (0.32 (95% interval 0.17 to 0.45)). Northern Shoveler, Blue-winged Teal, and Canvasback were intermediate, and the value for Gadwall was close to that for Mallard.\n\n\n::: {#tbl-elasticity .cell tbl-cap='Median and 95% interval for pond elasticity averaged across the prairie region over the past ten surveys. Short-term elasticity refers only to ponds in the current spring, while sustained elasticity includes carry-over effects of ponds from the previous spring.'}\n::: {.cell-output-display}\n\n\n|Species           |          Short-term|           Sustained|\n|:-----------------|-------------------:|-------------------:|\n|Northern Pintail  | 1.25 (0.97 to 1.55)| 1.30 (1.01 to 1.60)|\n|Northern Shoveler | 0.82 (0.69 to 0.95)| 0.95 (0.80 to 1.08)|\n|Blue-winged Teal  | 0.66 (0.43 to 0.92)| 0.84 (0.61 to 1.08)|\n|Canvasback        | 0.54 (0.30 to 0.79)| 0.78 (0.51 to 1.01)|\n|Gadwall           | 0.34 (0.17 to 0.52)| 0.45 (0.27 to 0.62)|\n|Mallard           | 0.22 (0.09 to 0.35)| 0.32 (0.17 to 0.45)|\n\n\n:::\n:::\n\n\nThe rankings remained unchanged following the refits (@tbl-sensitivity). Doubling the trend basis changed no sustained elasticity by more than 0.07, and none exceeded 0.03 when using AR(1) residuals; neither changed the order of the species. Changes in elasticity were greater with year effects, reaching a maximum of 0.16, with pintail decreasing to 1.14 and Canvasback increasing to 0.90. Species in the middle of the rankings then reorder, but pintail stays highest and Mallard lowest.\n\n\n::: {#tbl-sensitivity .cell tbl-cap='Recent sustained pond elasticity (median) in the main model and the three refits. For each refit, intervals are provided in the downloadable sensitivity analysis table.'}\n::: {.cell-output-display}\n\n\n|Species           | Main model| Trend basis doubled| AR(1), ρ = 0.2| Year effects|\n|:-----------------|----------:|-------------------:|--------------:|------------:|\n|Northern Pintail  |       1.30|                1.23|           1.28|         1.14|\n|Northern Shoveler |       0.95|                0.92|           0.94|         0.89|\n|Blue-winged Teal  |       0.84|                0.87|           0.88|         0.79|\n|Canvasback        |       0.78|                0.78|           0.78|         0.90|\n|Gadwall           |       0.45|                0.42|           0.43|         0.43|\n|Mallard           |       0.32|                0.33|           0.33|         0.36|\n\n\n:::\n:::\n\n\n### Change over time\n\nOver 70 years, elasticities changed, and not all in the same direction (@fig-curves, @tbl-shift). Short-term elasticity for pintail increased from 0.79 in the first ten surveys (1956–1965) to 1.25 in the last ten, representing an increase of 0.47 (95% interval 0.20 to 0.76). The recent value was higher in all 300 draws. In contrast, short-term elasticity for Mallard decreased by 0.21 (0.06 to 0.36). Short-term elasticity also increased for Blue-winged Teal, Northern Shoveler, and Canvasback, with higher recent values in 95% to 97% of the draws, while Gadwall showed little change.\n\nWith year effects included, the rise in pintail's elasticity was smaller, 0.32 (−0.04 to 0.67), with higher recent values in 96% of the draws. The decline in Mallard's elasticity was 0.15 (0.00 to 0.31). Every species changes in the same direction under both models; how firmly depends on the model.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Prairie mean short-term pond elasticity by year. Coloured lines and shaded bands show the median and 95% interval from the main model, while grey lines show the medians from the three refit models used for sensitivity analysis. The dashed line at 1 indicates a response proportional to pond numbers. Panels are ordered by sustained elasticity in recent years.](methods_files/figure-typst/fig-curves-1.png){#fig-curves fig-alt='Six small line charts of pond elasticity from 1956 to 2026. Northern Pintail rises from about 0.8 to 1.3. Northern Shoveler rises slowly from 0.6 to 0.8. Blue-winged Teal, Canvasback, Gadwall, and Mallard wave between about 0.1 and 0.9, with Mallard lowest. The refit lines mostly sit inside the main model\\'s band.'}\n:::\n:::\n\n\n\n::: {#tbl-shift .cell tbl-cap='Change in prairie-wide mean short-term elasticity between the first ten surveys and the last ten surveys, calculated within each of the draws. The final column gives the proportion of the 300 draws in which recent short-term elasticity was higher.'}\n::: {.cell-output-display}\n\n\n|Species           | First ten surveys| Last ten surveys|  Change (95% interval)| Draws higher recently|\n|:-----------------|-----------------:|----------------:|----------------------:|---------------------:|\n|Northern Pintail  |              0.79|             1.25|    0.47 (0.20 to 0.76)|                  100%|\n|Northern Shoveler |              0.62|             0.82|   0.21 (−0.01 to 0.40)|                   96%|\n|Blue-winged Teal  |              0.44|             0.66|   0.23 (−0.06 to 0.51)|                   95%|\n|Canvasback        |              0.26|             0.54|    0.29 (0.00 to 0.55)|                   97%|\n|Gadwall           |              0.40|             0.34|  −0.06 (−0.35 to 0.17)|                   32%|\n|Mallard           |              0.43|             0.22| −0.21 (−0.36 to −0.06)|                    1%|\n\n\n:::\n:::\n\n\n### Across strata\n\nDeviations in elasticity for individual strata from the prairie-wide elasticity were smaller than differences among species (@fig-strata). Within species, stratum medians spanned 0.30 to 0.64, with medians for pintail ranging from 1.12 to 1.59 and those for Mallard ranging from 0.17 to 0.48. No province consistently stood out across all species, and uncertainty around stratum estimates was much greater than uncertainty around the prairie-wide mean. The map on the web page shows the values for each stratum and their intervals.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Recent sustained pond elasticity by survey stratum (median across draws for the most recent ten surveys). Species are shown using shades of their respective colours, with common class boundaries indicated in the legend. The value for each survey stratum is the prairie-wide elasticity plus the stratum-specific deviation and carry-over effect.](methods_files/figure-typst/fig-strata-1.png){#fig-strata fig-alt='Six small maps of the 15 prairie strata, each species shaded in its own colour. Pintail strata are darkest, mostly 1 to 1.5; Mallard strata are lightest, mostly below 0.5.'}\n:::\n:::\n\n\n### Implications for wetland loss\n\nAcross the last ten surveys, Prairie Canada averaged 10,117,000 breeding dabbling ducks of the five species, and the mean number of May ponds was 3,374,000. In terms of marginal change, each pond lost proportionally across strata corresponds to a reduction of approximately 1.94 breeding dabbling ducks (90% interval 1.68 to 2.13). A sustained loss of 10% of May ponds across all 15 survey strata would correspond to 660,000 fewer breeding dabbling ducks (90% interval 575,000 to 727,000). The calculator provided on the web page allows readers to change the proportion lost, target region, and species.\n\n## Discussion\n\n### Differences among species\n\nThe clearest result was the magnitude of the differences among species. Depending on the model, the pintail population response to ponds was about 3 to 4 times as strong as the Mallard population response, with pintail showing the strongest response and Mallard the weakest across all refits. Previous accounts have long described pintails as opportunistic in their choice of settling locations, while Mallards are more inclined to return to previous breeding sites [@johnson1988]; in drought years, many pintails fly over the prairies to settle farther north [@hestbeck1995]. These elasticities are consistent with this view, but cannot distinguish the effects of settling from those of breeding success or survival. Previous work in the region has examined relationships between duck abundance and wetland conditions by species [@bethke1995], and a recent study of nine species found that responses to climate and land use differed among species, with pintails consistently showing extreme responses [@buderman2023]. For planning, the practical implication is that one value for duck abundance per pond obscures substantial differences among species. Benefits from wetland projects should be estimated separately for breeding pintails and breeding Mallards.\n\n### Pintails\n\nThe number of pintails in the Canadian prairies declined from an average of 3.32 million in 1955–64 to 0.51 million over the most recent ten surveys. If pintails were no longer responding to water availability, pond elasticity would have declined; however, pond elasticity did not decline. Pond elasticity increased in the main model, and probably increased in the most conservative refit. The number of birds available to respond changed. There are currently approximately 0.15 breeding pintails per May pond in the Canadian prairies, compared to 0.90 in 1955–64 (@fig-perpond). The number of Mallards per pond changed from 1.50 to 0.95.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Breeding birds per May pond in Prairie Canada for Mallard and Northern Pintail, 1955–2026 (observed totals, not model estimates).](methods_files/figure-typst/fig-perpond-1.png){#fig-perpond fig-alt='Line chart of birds per pond. Pintail falls from above 1 in the 1950s to about 0.1 to 0.2 recently. Mallard varies between about 0.5 and 2.3, lower recently but with no collapse.'}\n:::\n:::\n\n\nThe increase in elasticity raises the question of whether more pintails now leave the prairies during dry years. A simple check does not support this interpretation. Among pintails within the traditional survey area, the proportion counted in Prairie Canada varied less strongly with prairie pond numbers after 1990 than before. The slope of the logit of this proportion against the logarithm of pond numbers was lower after 1990 (1.12, SE 0.29) than before (1.90, SE 0.32). Additionally, the same weakening appears in all six species. These analyses are plain regressions on autocorrelated annual series; thus, the standard errors are optimistic.\n\nThis pattern points towards processes occurring after birds settle and away from settling decisions, and these processes were not measured in this survey. Studies using more detailed data point in the same direction. Modelling habitat selection and changes in population abundance separately, @buderman2020 found that pintails selected cropland for nesting and that areas with more cropland had fewer pintails the following year. An integrated population model indicated that pintail productivity increased with ponds and decreased with agricultural intensification [@zhao2019]. Pintails nest early and often in cropland, where tillage and seeding destroy many nests [@duncan2018]; additionally, duckling survival differs between cropland and grassland [@johns2024]. Changes in adult survival and harvest provide another route, and banding records for pintails on the prairies extend back to 1960 [@bartzen2017]. Testing these explanations requires data beyond the WBPHS summaries by stratum, and the next steps below suggest how.\n\n### Mallards\n\nMallard elasticity fell over the full record. One explanation is that Mallards now depend less on the number of ponds present in a given spring than previously, possibly due to their use of a broader range of wetlands and nesting vegetation, although this explanation cannot be tested with this analysis. Even with an elasticity of about 0.3, a 10% reduction in ponds would cost about 3% of a stratum's breeding Mallards, which would represent a large number of individuals due to the large Mallard population.\n\n### Using the elasticities\n\nPlanning tools in the prairie pothole region operate at the scales of individual wetlands and landscapes. In Prairie Canada, @devries2023 model duck density using survey segments and local habitat information, and combine these estimates with nest survival to estimate breeding productivity under conservation scenarios. I conducted this analysis at the scale of strata ranging in area from 13,000 to 100,000 km². This analysis therefore cannot address individual quarter sections, but can provide a range of estimates and associated uncertainty for questions concerning the entire region, such as what a given rate of wetland loss would mean for breeding ducks.\n\n## Limitations\n\n- **Wet years are not drainage:** These elasticities were derived from natural variation in pond numbers driven mostly by snowmelt and rainfall. The effects of drainage are permanent, and drainage tends to take small, shallow, temporary wetland basins frequently used by breeding pairs in early spring. The true effects of drainage may be greater or smaller than the effects associated with equivalent changes due to wetting and drying.\n- **Birds may move rather than disappear:** Declines in one region may be partially offset by increases elsewhere; thus, these scenarios indicate reductions in the number of ducks breeding in the selected regions, rather than changes in the continental population.\n- **Ponds are not wetlands:** The survey counts ponds holding water in May, not basins, wetland area, or wetland class. A drained basin and a dry basin look the same in the data.\n- **The estimates carry their own error:** The number of individuals in the breeding population was calculated by extrapolating transect counts and correcting for visibility, and uncertainty in these corrections was not fully reflected in the reported standard errors. The weights accounted only for the reported precision.\n- **Strata are large:** The relationships observed at the scale of strata do not necessarily hold at the scale of individual wetlands or farms.\n- **Residual structure remains:** The k-index and residual autocorrelation indicated that some structure remained in the residuals of the main model. The refit results show that species rankings and directions of change were robust, but interval widths from any single model are probably slightly too narrow.\n- **The uncertainty is approximate:** Draws were taken from a normal approximation to the posterior distribution, and tail quantiles based on 300 draws were subject to some Monte Carlo error.\n\n## Reproducibility\n\nAll content presented here was generated from a single `targets` pipeline [@landau2021]. Starting from a clean copy of the repository, `targets::tar_make()` downloads the survey files from ServCat, rebuilds the tidy data, fits 24 models (one main model and three refit models for each of six species), computes all summaries, exports the web page's data files, checks totals against published reports and JavaScript against R, and generates the figures. Package versions are locked using `renv`. All values and figures in this document are read from the pipeline store at render time, ensuring that the text remains consistent with the results. I used R version 4.4.3 (2025-02-28 ucrt), mgcv 1.9.1, and targets 1.12.0 for the analysis.\n\n## Next steps\n\n- **Segment-level counts:** Data at the level of survey transect segments, as used in @devries2023, would allow modelling at the scale of individual wetland landscapes and directly examining small, temporarily inundated basins.\n- **Land cover:** Previous research has shown that pintail abundance and breeding productivity are associated with cropland [@podruzny2002; @zhao2019; @buderman2020]. Including annual crop inventories in this model would test whether the decline in pintails per pond corresponds to cropland area, particularly the area planted with spring-sown crops.\n- **Redistribution:** A joint model encompassing all survey strata, including the U.S. prairies and boreal forest, would estimate the destinations of birds in dry years, rather than treating each region separately.\n- **Visibility corrections:** If uncertainty in the correction factors linking aerial and ground surveys were propagated through the full model, the resulting intervals would be wider and more realistic.\n\n## Appendix: model checks for Northern Pintail\n\n@fig-appraise shows the residual diagnostics for the pintail model. The quantile plot compares deviance residuals with simulated quantiles from the fitted model. The straight band among the residuals for low predicted values is due to zero counts.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Residual diagnostics for the Northern Pintail model using gratia::appraise(): simulation-based quantile plot, scatterplot of residuals against the linear predictor, histogram of residuals, and scatterplot of observed against fitted values.](methods_files/figure-typst/fig-appraise-1.png){#fig-appraise fig-alt='Four diagnostic plots. The quantile plot follows the reference line closely. Residuals against the linear predictor scatter evenly around zero apart from a diagonal band of zero counts. The histogram is roughly symmetric. Observed and fitted values lie close to the one-to-one line.'}\n:::\n:::\n\n\n## References\n\n::: {#refs}\n:::\n",
    "supporting": [
      "methods_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}